### ISSUE TITLE
Support for plugins

### ISSUE THREAD

**Issue by mrmeyers99** [rbhadti94/apache-jmeter-action#18]
I tried to use this action, but our team uses custom plugins and I don't think I can get that to work with this action.  I added the jar file with our plugins to the classpath using:

```
      - name: Run JMeter Action
        uses: rbhadti94/apache-jmeter-action@v0.3.2
        with:
          testFilePath: test.jmx
          outputReportsFolder: reports/
          args: -Duser.classpath=customplugin.jar
```
However, when I run jmeter, I get the following error:

> Uncaught Exception java.lang.NoClassDefFoundError: kg/apc/jmeter/JMeterPluginsUtils in thread Thread[StandardJMeterEngine,5,main]. See log file for details

When I googled it, it looks like it's because the plugin manager isn't properly setup.  Details [here:](https://stackoverflow.com/questions/46084583/jmeter-no-class-def-found-error-kg-apc-jmeter-jmeterpluginsutils)

Would it be possible to add support for plugins?
