### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by DawidOskwarek** [rbhadti94/apache-jmeter-action#27]
Hey can you provide an example of how can I use UltimateTheadGroup plugin in your action?

**Comment by DawidOskwarek** [comment]
bump

**Comment by mohanmurari07** [comment]
Hey @rbhadti94 - has the UltimateTheadGroup issue solved, or is this still an issue

**Comment by ptupakul** [comment]
Hey @rbhadti94 - has the UltimateTheadGroup issue solved, or is this still an issue.

**Comment by rajkamal-takeda** [comment]
Hey @rbhadti94 the ultimate thread group is still an issue. Are you planning to include the plugin in the docker so that it can pick at runtime when JMX file having ultimate thread group is passed to the action

**Comment by king-raj7** [comment]
Hey @rbhadti94 : the ultimate thread group is still an issue. Are you planning to include the plugin in the docker so that it can pick at runtime when JMX file having ultimate thread group is passed to this action

**Comment by rbhadti94** [comment]
Hi @king-raj7 @ptupakul @DawidOskwarek 


I see that ultimate thread group is part of `jpgc-casutg`. Can you specify the plugin argument?
```
      - name: Run JMeter Action
        uses: ./
        with:
          testFilePath: tests/sample_test.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"
          plugins: "jpgc-casutg"
```

I'll update the docs if this works.
