### ISSUE TITLE
Improve Doc for newbie

### ISSUE THREAD

**Issue by misteio** [rbhadti94/apache-jmeter-action#8]
Hello,
Very good job, it works like a charm. But for newbie like me, I spend around an Hour for understand checkout and upload artifact.

You should provide a better documentation with  actions/checkout@1.0.0 + actions/upload-artifact@v2

Best regards.

**Comment by rbhadti94** [comment]
Hi @misteio,
Thanks for the feedback. I didn't quite understand your request.

Would you like to see examples of this action using checkout and upload artifact?

**Comment by misteio** [comment]
On your example page you post :
## Example usage
```yaml
# Use JMeter to run the JMX test case and produce reports in the "reports/"
# directory in the workspace.
- name: Run JMeter Tests
  uses: rbhadti94/apache-jmeter-action@v0.2.0
  with:
    testFilePath: tests/sample_test.jmx
    outputReportsFolder: reports/
```
A full example with checkout (For download file from github repository) + output report as artifact could be great.
## Full Example usage
```yaml
# Use JMeter to run the JMX test case and produce reports in the "reports/"
# directory in the workspace.
name: JMeter
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1.0.0
    - name: Run JMeter Tests
      uses: rbhadti94/apache-jmeter-action@v0.2.0
      with:
        testFilePath: tests/sample_test.jmx
        outputReportsFolder: reports/
    - uses: actions/upload-artifact@v2
      with:
        name: report
        path: reports/
```
